#!/bin/bash

# NOTE: gas.cdef computes gas per month 730 = (24 * 365 / 12) divided by 100 to
# get to euros
case $1 in
  config)
  cat <<'EOM'
graph_title Energy Cost
graph_vlabel Euro/month
graph_category smartmeter
graph_info The price of energy usage per month in euros
graph_args --base 1000 -l 0
graph_period hour
power.label Power
gas.label Gas
gas.type COUNTER
gas.cdef gas,730,*,100,/
EOM
  exit 0;;
esac

FILENAME=/tmp/energy.dat

if [ ! -r $FILENAME ] 
then
echo "Error: Cannot read '$FILENAME'" >&2
  exit 1
fi

echo -n "power.value "
cut -d' ' -f3 < $FILENAME
echo -n "gas.value "
cut -d' ' -f4 < $FILENAME
