#!/bin/bash

case $1 in
  config)
  cat <<'EOM'
graph_title Energy Cost
graph_vlabel Euro/month
graph_category smartmeter
graph_info The price of energy usage per month in euros
graph_args --base 1000 -l 0
power.label Power
gas.label Gas
total.label Total
EOM
  exit 0;;
esac

FILENAME=/tmp/energy.dat

if [ ! -r $FILENAME ] 
then
echo "Error: Cannot read '$FILENAME'" >&2
  exit 1
fi

power=$(cut -d' ' -f3 < $FILENAME)
gas=$(cut -d' ' -f4 < $FILENAME)
echo "power.value $power"
echo "gas.value $gas"
echo -n "total.value "
echo "scale=2;($gas + $power)" | bc
