#!/bin/bash

case $1 in
  config)
  cat <<'EOM'
graph_title Gas Usage
graph_vlabel Gas in m^3 
graph_category smartmeter
graph_info The gas usage in m^3
graph_args --base 1000 -l 0
gas.label 5 min average
gas.type COUNTER
EOM
  exit 0;;
esac

FILENAME=$(pwd)/../energyavg.dat

if [ ! -r $FILENAME ] 
then
echo "Error: Cannot read '$FILENAME'" >&2
  exit 1
fi

echo -n "gas.value "
cut -d' ' -f2 < $FILENAME
