#!/bin/bash

MUNIN_PLUGINS_DIR=/etc/munin/plugins
if [ ! -d $MUNIN_PLUGINS_DIR ]
then
  echo "Error: No munin plugins dir found" >&2
  exit 1
fi

if [ ! -w $MUNIN_PLUGINS_DIR ]
then
  echo "Error: Can't write as '$USER' to '$MUNIN_PLUGINS_DIR', try sudo?" >&2
  exit 1
fi

for file in *
do
  if [ $file = 'install' ]
  then
    continue
  fi

  rm -vf $MUNIN_PLUGINS_DIR/$file
  ln -vs $(pwd)/$file $MUNIN_PLUGINS_DIR/$file
done
