#!/bin/bash

case $1 in
  config)
  cat <<'EOM'
graph_title Power Usage
graph_vlabel kW
graph_category smartmeter
graph_info The power usage in kilowatt every 10 seconds
graph_args --base 1000 -l 0
power.line 0.54:ffae00:average
power.label 5 min avg
EOM
  exit 0;;
esac

FILENAME=/tmp/energy.dat

if [ ! -r $FILENAME ] 
then
echo "Error: Cannot read '$FILENAME'" >&2
  exit 1
fi

echo -n "power.value "
cut -d' ' -f1 < $FILENAME
