#!/bin/bash

case $1 in
  config)
  cat <<'EOM'
graph_title Power I/O
graph_vlabel Watt
graph_category smartmeter
graph_info The power usage and return in Watt
graph_args --base 1000 -l 0
usage.line 540:ffae00:average
usage.label Power usage
return.label Power return
EOM
  exit 0;;
esac

FILENAME=/tmp/energy.dat

if [ ! -r $FILENAME ] 
then
echo "Error: Cannot read '$FILENAME'" >&2
  exit 1
fi

echo -n "usage.value "
cut -d' ' -f1 < $FILENAME
echo -n "return.value "
cut -d' ' -f2 < $FILENAME
